Repository oply/joey, pull requests merged in 2018-06, with the labels that each got.

#28 Write all the documentation basics
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: difficulty: beginner friendly 👶, status: wip, type: documentation 📓

#35 Create form inputs SCSS + some cleaning
  .gitignore
  src/View/page/index.html
  web/css/style.css
  web/scss/style.scss
  web/scss/tools/_medias.scss
  web/scss/tools/_reset.scss
  web/scss/tools/_transitions.scss
  web/scss/tools/_variable.scss
  web/scss/tools/_variables.scss
  web/scss/ui/_btn.scss
  web/scss/ui/_field.scss
  web/scss/ui/_input.scss
  web/scss/ui/_label.scss
Labels: dev: front, status: wip

#36 Create sign up page + upgrading styles
  src/View/page/sign-up.html
  web/scss/components/_btn.scss
  web/scss/components/_field.scss
  web/scss/components/_input.scss
  web/scss/components/_label.scss
  web/scss/components/_layout.scss
  web/scss/components/_subtitle.scss
  web/scss/components/_title.scss
  web/scss/containers/_header.scss
  web/scss/pages/_sign-up.scss
  web/scss/style.scss
  web/scss/tools/_reset.scss
  web/scss/tools/_variables.scss
  web/scss/ui/_input.scss
Labels: dev: front, status: wip, type: feature

#33 Add new documentation
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: status: wip, type: documentation 📓

#40 Add responsive to Signup page
  src/View/page/sign-up.html
  web/scss/components/_layout.scss
  web/scss/containers/_header.scss
  web/scss/pages/_sign-up.scss
  web/scss/tools/_medias.scss
  web/scss/tools/_variables.scss
Labels: dev: front, status: to review

#42 [WIP] Create SCSS Table component
  src/View/page/client-list.html
  web/scss/components/_table.scss
  web/scss/components/_tag.scss
  web/scss/style.scss
  web/scss/tools/_classes.scss
  web/scss/tools/_variables.scss
Labels: dev: front, status: wip

#45 Create IIFE to format input type tel && add select algorithme
  web/js/format.js
  web/js/select.js
Labels: status: to review, type: feature

#44 Create select input style
  web/scss/components/_select.scss
Labels: status: mergeable, type: feature

#46 Some SCSS refacto
  src/View/page/client-list.html
  src/View/page/index.html
  src/View/page/sign-up.html
  web/scss/components/_label.scss
  web/scss/components/_subtitle.scss
  web/scss/components/_table.scss
  web/scss/components/_title.scss
  web/scss/tools/_reset.scss
  web/scss/tools/_variables.scss
Labels: dev: front, status: wip, type: enhancement ✨

#47 Integrate Create Client modal
  src/View/page/client-create-s1.html
  src/View/page/client-create-s2.html
  web/scss/components/_btn.scss
  web/scss/containers/_stepper.scss
  web/scss/pages/_create-client.scss
  web/scss/style.scss
  web/scss/tools/_variables.scss
Labels: dev: front, status: wip, type: feature

#49 New header version + some icons added
  src/View/page/client-create-s1.html
  src/View/page/client-create-s2.html
  src/View/page/client-list.html
  src/View/page/sign-up.html
  web/fonts/icomoon.eot
  web/fonts/icomoon.svg
  web/fonts/icomoon.ttf
  web/fonts/icomoon.woff
  web/scss/components/_btn.scss
  web/scss/components/_user.scss
  web/scss/containers/_header-connect.scss
  web/scss/containers/_header.scss
  web/scss/style.scss
  web/scss/tools/_fonts.scss
  web/scss/tools/_variables.scss
Labels: dev: front, status: wip, type: feature

#50 Update header with nav link current
  src/View/page/client-create-s1.html
  web/scss/containers/_header.scss
Labels: dev: front, status: wip

#60 Add success message + group modal steps
  src/View/page/client-create-s1.html
  src/View/page/client-create-s2.html
  src/View/page/client-create.html
  web/scss/containers/_modal.scss
  web/scss/pages/_client-create.scss
  web/scss/pages/_create-client.scss
  web/scss/style.scss
  web/scss/tools/_reset.scss
Labels: dev: front, status: to review, type: enhancement ✨, type: feature

#63 Remove jQuery from select component
  src/View/page/index.html
  web/js/select.js
  web/scss/style.scss
Labels: type: enhancement ✨

#64 Create login/signup actions
  src/View/page/connexion.html
  src/View/page/sign-up.html
  web/js/actions.js
Labels: type: feature

#62 Add icon & init html
  src/View/page/client-card.html
  web/fonts/icomoon.eot
  web/fonts/icomoon.svg
  web/fonts/icomoon.ttf
  web/fonts/icomoon.woff
  web/scss/components/_block-info.scss
  web/scss/components/_btn.scss
  web/scss/components/_tag.scss
  web/scss/components/_title.scss
  web/scss/containers/_header.scss
  web/scss/pages/_client-card.scss
  web/scss/style.scss
  web/scss/tools/_classes.scss
  web/scss/tools/_fonts.scss
Labels: status: wip, type: feature

#71 [WIP] Update / upgrade select styles and scripts
  src/View/page/index.html
  web/js/select.js
  web/scss/components/_input.scss
  web/scss/components/_select.scss
Labels: dev: front, status: wip, type: enhancement ✨

#74 Create form stepper by modal to add client
  src/View/page/client-list.html
  web/js/client.js
  web/scss/components/_btn.scss
  web/scss/components/_layout.scss
  web/scss/containers/_modal.scss
  web/scss/pages/_client-create.scss
Labels: status: mergeable, type: feature

#78 Sign in and sign up backend connected to frontend
  app/config/conf.php
  composer.json
  composer.lock
  index.php
  src/Controller/ClientController.php
  src/Controller/Controller.php
  src/Controller/SalesController.php
  src/Controller/SecurityController.php
  src/Controller/admin/AdminController.php
  src/Helper/BaseController.php
  src/Helper/Connect.php
  src/Helper/FrontController.php
  src/Helper/Session.php
  src/Model/Admin.php
  src/Model/Client.php
  src/Model/Sales.php
  src/View/admin/client/adminClient.html.twig
  src/View/admin/client/adminClientAdd.html.twig
  src/View/admin/client/adminClientEdit.html.twig
  src/View/admin/homeAdmin.html.twig
  src/View/index.html.twig
  src/View/sales/salesClient.html.twig
  src/View/sales/salesClientAdd.html.twig
  src/View/sales/sign-up.html.twig
  src/View/sign-in.html.twig
  web/index.php
Labels: dev: back, dev: front, type: feature

#76 Fix modals
  src/View/page/client-card.html
  src/View/page/client-list.html
  web/scss/containers/_stepper.scss
  web/scss/pages/_client-list.scss
  web/scss/style.scss
  web/scss/tools/_classes.scss
Labels: dev: front, status: wip, type: bug 🐛
